name: TestCharms
  
on: pull_request
jobs:
  build-charms:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: lint
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: actions/checkout@v1
      - name: install juju
        run: | 
          sudo snap install juju --classic
      - name: Install charmcraft
        run: |
          pip install charmcraft
      - name: pull controller credentials
        run: |
          aws s3 cp s3://omnivector-cicd/juju-local/juju-local.tar.gz .
          tar -xzvf juju-local.tar.gz
          echo "JUJU_DATA=/github/home/.local/share/juju" >> $GITHUB_ENV
          echo ${{secrets.JUJU_CIRCLECI_USER_PASSWORD}} | juju login --user circleci
      - name: Build charms
        run: |
          make charms
          ls -la
